### ISSUE TITLE
Replace images/ressources?

### ISSUE THREAD

**Issue by ccman32** [mattcabb/mib2std-toolbox#3]
Hi there,
I am currently retrofitting auxiliary heating in my Seat Leon 5F and I noticed that the images in the menu for it are missing so it looks like this:
![IMG_20200427_201539](https://user-images.githubusercontent.com/17458377/80852357-2ffe5900-8c28-11ea-94bc-67aa3cd7e4d1.jpg)
It is a MIB2Std (part number 5QA035858A) and so far I could not find any way to add the missing image. Would it be possible to do this with your toolkit once it is finished or is there already a way to do it?

**Comment by mattcabb** [comment]
You can check if there's a newer firmware available for your main unit. Maybe it will contain missing images.
If you dig in google you will find zip archives with FW 0330 and 0346.

**Comment by ccman32** [comment]
Thanks for the response! I already had that checked by my local automobile workshop a few weeks ago and they said there is no official update available (didn't look for one myself though). It currently runs with FW 0359.
I highly doubt that this will be added by an update because the Leon isn't sold with auxiliary heating so it makes sense that they didn't make an image for it. The only reason why it's in the software is probably because it was easier for them to just leave the functionality in the firmware instead of removing it and also because it is available for the SEAT Ateca which uses the same (or at least a very similar) firmware. So yeah, I doubt that this will ever be added unless I do it by myself. I have a software development background so that shouldn't be the problem but I am completely unfamiliar with the system running on the MIB2Std and also how to access and modify it in general.

**Comment by mattcabb** [comment]
If you get you hand on the update, you will be able to extract GUI files, make custom ones, and have it ready for when the tool is working.

**Comment by ccman32** [comment]
> 
> 
> If you get you hand on the update, you will be able to extract GUI files, make custom ones, and have it ready for when the tool is working.

Sounds good! But what do you mean by saying "If you get your hand on the update"? As I said, there seems to be no update available for my unit. Do you mean that I have to find the update/installation file for my version so I can edit it and then install the modified version? Or are you talking about an update of your toolkit?

**Comment by mattcabb** [comment]
If you find any update (doesn't matter if the firmware is older than your current one) you will be able to extract GUI files from it. With that you can start working on the missing graphics and prepare custom GUI pack to be uploaded later on to your main unit (or custom single PNG file to replace in your original GUI pack).
Even if you find relatively old firmware, GUI pack should be in the same format, so you could start working on it now. And later on (when there's a way to access your main unit file system) you can just replace GUI pack with your custom one.

**Comment by flipidus** [comment]
i have a 0478 Firmware for Volkswagen MIB2 STD (Technisat / Preh) devices. i also found the big file in the firmware with the GUI Textures and Images. I extracted it with the Python script out of the MIB2HIGH-Toolbox. The next thing i will try is to pack this file with the modified files back again and install this firmware on a test MIB2STD (Composition Media, no NAV)

**Comment by olli991** [comment]
> 
> 
> i have a 0478 Firmware for Volkswagen MIB2 STD (Technisat / Preh) devices. i also found the big file in the firmware with the GUI Textures and Images. I extracted it with the Python script out of the MIB2HIGH-Toolbox. The next thing i will try is to pack this file with the modified files back again and install this firmware on a test MIB2STD (Composition Media, no NAV)

Is there a safe way in to the MIB2STD? D-Link shouldn´t work because telnet isn´t active i´ve been told. Would be interesting to get graphic-mods also supported on STD devices. I´ve done several on the high and can share those here if needed. Or they can be seen in the wiki at the mibhigh-toolbox repo :-)

Okay maybe nevermind: You already discuss a way in in #2 .

**Comment by flipidus** [comment]
> Is there a safe way in to the MIB2STD? D-Link shouldn´t work because telnet isn´t active i´ve been told. Would be interesting to get graphic-mods also supported on STD devices. I´ve done several on the high and can share those here if needed. Or they can be seen in the wiki at the mibhigh-toolbox repo :-)
> 
> Okay maybe nevermind: You already discuss a way in in #2 .

Im also still looking for a safe way inside the MIB2 STD. I still need some hardware things to get the MIB2STD running at home, for example a HSD cable for connecting the MIB with the ABT (Display Unit) 

I will try to modify the firmware files with new graphics and then i will try to install the firmware on my test MIB2 STD Device. I hope i will not brick it :-)

**Comment by ccman32** [comment]
I've been searching for a while now but so far I could not find any firmware for my MIB2Std. All I found is an update for the MIB1 and many other download links that don't work anymore so if anyone knows a link/source for the firmware please let me know.
The part number for my unit is 5QA035858A (with hardware H30 and software 0359).

**Comment by ccman32** [comment]
> > Is there a safe way in to the MIB2STD? D-Link shouldn´t work because telnet isn´t active i´ve been told. Would be interesting to get graphic-mods also supported on STD devices. I´ve done several on the high and can share those here if needed. Or they can be seen in the wiki at the mibhigh-toolbox repo :-)
> > Okay maybe nevermind: You already discuss a way in in #2 .
> 
> Im also still looking for a safe way inside the MIB2 STD. I still need some hardware things to get the MIB2STD running at home, for example a HSD cable for connecting the MIB with the ABT (Display Unit)
> 
> I will try to modify the firmware files with new graphics and then i will try to install the firmware on my test MIB2 STD Device. I hope i will not brick it :-)

Glad to hear that you have a test device! Unfortunately I only have the unit that is installed in my car and I can't risk bricking that. Looking forward to your results :)

**Comment by ccman32** [comment]
Hey guys, just wanted to ask if anyone was able to make some progress here over the past weeks/months?
I actually managed to install the auxiliary heater successfully in my car so the only thing left to do is adding the missing graphics.
If there is anything I can do to help so that faster progress can be made on this project, please let me know!

**Comment by mattcabb** [comment]
> Hey guys, just wanted to ask if anyone was able to make some progress here over the past weeks/months?
> I actually managed to install the auxiliary heater successfully in my car so the only thing left to do is adding the missing graphics.
> If there is anything I can do to help so that faster progress can be made on this project, please let me know!

Someone did make some progress. Check this: https://github.com/olli991/mib2std-toolbox

**Comment by ccman32** [comment]
> 
> 
> > Hey guys, just wanted to ask if anyone was able to make some progress here over the past weeks/months?
> > I actually managed to install the auxiliary heater successfully in my car so the only thing left to do is adding the missing graphics.
> > If there is anything I can do to help so that faster progress can be made on this project, please let me know!
> 
> Someone did make some progress. Check this: https://github.com/olli991/mib2std-toolbox

Thanks for the info! I was already able to replace the images in the auxiliary heating menu of my mib2 a few weeks ago, though:
![IMG_20210205_175953](https://user-images.githubusercontent.com/17458377/111380076-2e088180-86a4-11eb-9fe5-f2d6136d0587.jpg)
Wasn't that easy because jille's compress-mcf script originally did not update all checksums in the mcf files but after working on that problem with him for a few days we managed to get it to work just fine :)
