### ISSUE TITLE
New mib2-toolbox install method will also work on mib2std!

### ISSUE THREAD

**Issue by olli991** [mattcabb/mib2std-toolbox#6]
Hello,
we've just developed a new install method for the mib2 high toolbox. This isn't using the POI import anmore.
It uses a donor navupdate so far and build some own modules for the update. For non nav units modified firmwareupdate should theoretically also be possible. ... just realised there won't be a navupdate for std units. So modified firmwareupdate it will be and should be possible.

ESD file is copied like that. We also managed to get a finalScript running within the updateprocess which is copying all the scripts to the unit ans also correctly chmods them.

I sadly have no access to a std unit but if someone can get me a full dump of a std unit I could build an installer for std units too.

We only need the path of ESD menus and also a path were to store scripts on the unit which is accesable for ESD menu. 

Just let me know if I should / can assist you @mattcabb

**Comment by mattcabb** [comment]
Hi! The other day I saw that there's new major version of MIB2-Toolbox.
Right now my unit is little bit modified so any tests would not be reliable.

Check out README.md in the research folder. I believe this will be helpful https://github.com/mattcabb/mib2std-toolbox/tree/master/Research

**Comment by marc1706** [comment]
@olli991 if you need help with testing on a MIB2 Std unit, I can offer that with a unit I currently have on a testbench setup (5QA 035 874). Also one of the devices that currently does not support any of the other methods that currently roam the internet.

**Comment by olli991** [comment]
I was informed the backdoor via metainfo should be possible on Delphi units. On Technisat it seems that they arent working. 
If someone could send me a complete dump of a recent delphi unit i could investigate the file structure and maybe can write something up to test. I sadly have nothing available here. You can hit me up via t.me/olli991

**Comment by olli991** [comment]
I've bought myself a testbench and some units... maybe we can get further here... need to read into technisat and delphi first :D

**Comment by tehfalcon-vw** [comment]
Hoping Delphi support comes soon!

**Comment by olli991** [comment]
Delphi should be possible with metainfo backdoor... sadly i have no delphi unit here to build a toolbox for it. so currently no progress
