### ISSUE TITLE
MIB2STD Toolbox for Technisat Nav units now available!

### ISSUE THREAD

**Issue by olli991** [mattcabb/mib2std-toolbox#8]
Hey there. I managed to get a working backdoor and developed, together with the MIB2 High Toolbox guys, a toolbox for standard units and we even ported some scripts to std units already.

Skin and startupscreen changes are already possible.

Head over to my repo if you want to check it out. Also many thanks to @yox2019 who helped developing all this!
I'm glad if you want to also contribute to it :-)

https://github.com/olli991/mib2std-toolbox

**Comment by mattcabb** [comment]
That's great!
Will try it out this week. I also have an idea how to make it work on non-nav systems (Composition Media) but it will take you guys to check if this approach makes sense.

**Comment by yox2019** [comment]
... then send some more details about your idea :)))

**Comment by mattcabb** [comment]
> ... then send some more details about your idea :)))

https://github.com/olli991/mib2std-toolbox/issues/1
